//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaCarros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_DIRECCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLE_DIRECCION()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public int ID_DIRECCION { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> ID_PROVINCIA { get; set; }
        public Nullable<int> ID_CANTON { get; set; }
        public Nullable<int> ID_DISTRITO { get; set; }
    
        public virtual CANTON CANTON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual PROVINCIA PROVINCIA { get; set; }
        public virtual DISTRITO DISTRITO { get; set; }
    }
}
