//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaCarros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int ID_EMPLEADO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public int TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public int SALARIO { get; set; }
        public Nullable<int> ID_ROL { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
