//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaCarros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int ID_FACTURA { get; set; }
        public System.DateTime FECHA { get; set; }
        public int UNIDADES { get; set; }
        public int IMPORTE_TOTAL { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<int> ID_REPUESTO { get; set; }
        public Nullable<int> ID_VEHICULO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual REPUESTO REPUESTO { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
    }
}
