//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaCarros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESO
    {
        public int ID_CLIENTE { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
