//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaCarros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public int ID_INVENTARIO { get; set; }
        public int CANTIDAD { get; set; }
        public int VALOR { get; set; }
        public System.DateTime ULTIMA_VENTA { get; set; }
        public Nullable<int> ID_REPUESTO { get; set; }
    
        public virtual REPUESTO REPUESTO { get; set; }
    }
}
