//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaCarros.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDOR()
        {
            this.REPUESTO = new HashSet<REPUESTO>();
        }
        [Required(ErrorMessage = "El id es obligatorio")]

        public int ID_PROVEEDOR { get; set; }
        [Required(ErrorMessage = "El Nombre es obligatorio")]

        public string NOMBRE_PROVEEDOR { get; set; }
        [Required(ErrorMessage = "El descripcion es obligatorio")]

        public string DESCRIPCION_PROVEEDOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPUESTO> REPUESTO { get; set; }
    }
}
