//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaCarros.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class REPUESTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPUESTO()
        {
            this.FACTURA = new HashSet<FACTURA>();
            this.INVENTARIO = new HashSet<INVENTARIO>();
            this.PROVEEDOR = new HashSet<PROVEEDOR>();
        }
        [Required(ErrorMessage = "El Id es obligatorio")]

        public int ID_REPUESTO { get; set; }
        [Required(ErrorMessage = "El Nombre es obligatorio")]

        public string NOMBRE { get; set; }
        [Required(ErrorMessage = "La descripcion es obligatorio")]

        public string DESCRIPCION { get; set; }
        [Required(ErrorMessage = "El precio untario es obligatorio")]

        public int PRECIO_UNITARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTARIO> INVENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVEEDOR> PROVEEDOR { get; set; }
    }
}
