//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaCarros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICULO()
        {
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public int ID_VEHICULO { get; set; }
        public int PLACA { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public int CILINDRAJE { get; set; }
        public string COLOR { get; set; }
        public string TIPO_COMBUSTIBLE { get; set; }
        public int PRECIO_UNITARIO { get; set; }
        public string ANNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURA { get; set; }

    }
    public enum TIPO_COMBUSTIBLE
    {
        Gasolina,
        Diesel,
        Super
    }
}
